### ISSUE TITLE
404 Not Found when accessing https://mirror.iscas.ac.cn/vimeros/yubos-extra/sid-riscv32-yubos-rootfs.tar.gz

### ISSUE THREAD

**Issue by sashimi-yzh** [yuzibo/riscv32#2]
It seems that the URL has changed.

**Comment by yuzibo** [comment]
Sorry for the late reply.

Please refer to method [B]( https://github.com/yuzibo/riscv32/wiki#b-start-from-pre-built-image), I have updated the link.

Sorry again.
